### ISSUE TITLE
How to prevent flickering of theme on refresh

### ISSUE THREAD

**Issue by bayaderpack** [willin/svelte-turbo#17]
How to prevent flickering of theme on refresh. When I select theme it is added in cookie but still each refresh like half second it flicker default one than switch.

**Comment by bayaderpack** [comment]
I fix it by adding in app.html header this code
```
<script>try{document.documentElement.setAttribute('data-theme',localStorage.getItem('theme'));}catch(e){}</script>
```

**Comment by willin** [comment]
you can ref to remix-themes: <https://github.com/abereghici/remix-themes> use cookies to set theme.

and try to use `transformPageChunk` ref to your previous question.

**Comment by willin** [comment]
chat on discord: https://discord.gg/sRpfQ9VVZH
